### ISSUE TITLE
Search input carry over

### ISSUE THREAD

**Issue by dharness** [valiahq/Valia-Web#167]
After you search for a city on the first screen, it should display that city in the top search bar on the second screen

**Comment by dharness** [comment]
@larryblyth this seems to work for me. Can you still generate this error? If so, can you give the specific steps to produce from a clean refresh of the page so I can track down the bug?

**Comment by larryblyth** [comment]
Maybe it was because I had refreshed on the second screen. A low-priority change could be to add the filters as url params so that refreshes don't ruin the user's search and so that they can copy and share the URL of their search with friends.

ex: Airbnb: https://www.airbnb.com/s/S%C3%A3o-Paulo--State-of-S%C3%A3o-Paulo--Brazil/homes?adults=2&allow_override%5B%5D=&checkin=2017-07-24&checkout=2017-08-06&guests=2&ib=true&ne_lat=-23.523567211939294&ne_lng=-46.62719060077575&search_by_map=true&sw_lat=-23.594476583428268&sw_lng=-46.69413853778747&zoom=13&s_tag=BYB2w2h4

**Comment by dharness** [comment]
@larryblyth Yeah I was thinking that too. Can you add that as an issue in either the post-mvp or ToDo depending on when you want it done?

**Comment by dharness** [comment]
Closing this issue until we can regenerate this bug
